version: '3.7'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.17
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html
      - ./php-nginx/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./php-nginx
    working_dir: /var/www/html
    volumes:
      - ./public_html:/var/www/html


volumes:
   php-nginx:
   public_html:
     